### ISSUE TITLE
New columns in Study

### ISSUE THREAD

**Issue by sargentfrancesca** [Spandex-at-Exeter/demography_database#34]
New columns in Study:
(meta tables)
Purpose_Endangered:

> > F
> > NA
> > NATS
> > T
> > Purpose_Weed:
> > F
> > NA
> > NATS
> > T

@simonrolph @DannyLBuss please could you provide a descriptive sentence for each? I can add these as a meta table.

**Comment by simonrolph** [comment]
Purpose endangered:

F: The study was carried out because a species was under threat
NA: 
NATS: No access to source
T: The species was studied because the species was under threat

Purpose weed:

F: The study was not carried out because a species posed a threat
NA:
NATS: No access to source
T: The study was carried out because a species posed a threat

**Comment by DannyLBuss** [comment]
@simonrolph for purpose endangered should F say "The study was carried out but the species were NOT under threat"? Also, do T and F stand for True and False. If so, should we change them to True and False so we keep all boolean variables consistent?

**Comment by sargentfrancesca** [comment]
Please could I get confirmation of the values for the meta tables? I can put them in without a description for now, but will need it soon. The values I'll enter are as follows:

True
False
NA
NATS

@simonrolph, please could you give some examples of where NATS is required?

**Comment by simonrolph** [comment]
yep @DannyLBuss you are right 

Purpose endangered:

F: The study was not carried out because a species was under threat

sloppy copy pasting from me
